---
networks:
  traefik_proxy:
    external: true

services:
  backend:
    networks:
      - default
      - traefik_proxy
    labels:
      ## Traefik
      - traefik.enable=true
      ## HTTPS Routers
      - traefik.http.routers.${SERVICE}.entrypoints=webs
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${APP_PORT}
